### ISSUE TITLE
Feature requesst: add a "+" StressSymbol

### ISSUE THREAD

**Issue by egorsmkv** [lang-uk/ukrainian-word-stress#2]
Currently, the "StressSymbol" class has two fields `AcuteAccent` and `CombiningAcuteAccent`

It would be nice to have also just a `PlusAccent`

**Comment by osyvokon** [comment]
Please note that you can use _any_ symbol, not just those listed in `StressSymbol`. In fact, there is an example in the [README](https://github.com/lang-uk/ukrainian-word-stress#stress-mark-symbols) showing how to use the plus sign:

```bash
$ echo 'олені небриті і не голені.' | ukrainian-word-stress --symbol +
о+лені небри+ті і не го+лені.
```

So while I'll add `PlusAccent` in a future release, you don't have to wait for it.

**Comment by egorsmkv** [comment]
Thanks!

Also, can you add a flag to set this plus after or before a stressed letter?

For TTS usages it’s important.
