### ISSUE TITLE
Dictionary parsing incorrect

### ISSUE THREAD

**Issue by magicse** [lang-uk/ukrainian-word-stress#7]
Thank You for Your work!
I think there is a problem, but correct me if I'm wrong.
You are using the file Stress,txt as a basis
And there are for example are two records in that file.
викладачу́-предме́тнику  - where two  stress in positions 9 (x09) and  16 (x10). Position (x09) same as tag separator \t
виклада́чу-предме́тнику  - where two stress in position 7 (x07) and 16 (x10). - There is some strange stress here at position 07.

You use "accents, _, tags = item.partition(b'\t')" in stressify_.py file to get accent and tags from values.
Compiled dictionary String  in file stress.trie for above two records   is  b'\t\x10\t\x11%j1\n\x07\x10\t\x11&j1\n'

Where for first record "**викладачу́-предме́тнику**"
- \t\x10 two stress positions  9 (x09) and  16 (x10)
- \t -separator
- \x11%j1 -Tags

Same for second record "**виклада́чу-предме́тнику**"
- \x07\x10 two stress positions 7(x07) and 16 (x10)
- \t - Separator
- \x11&j1 - Tags

Interesting situation for first record...
Due stress position is 09 = x09 = \t , your code "accents, _, tags = item.partition(b'\t')" get incorrect  data from values... due mismatch {pos} =09 aka \t and real Tag separator \t

I didn't get first correct stress викладачу́-предме́тнику due  mismatch x09 -Pos and x09-Tag
```
from ukrainian_word_stress import Stressifier, OnAmbiguity
stressify = Stressifier(on_ambiguity=OnAmbiguity.All)
text = "викладачу-предметнику"
stressify(text)
output - 'виклада´чу-предме´тнику'
```

May be for Tag byte better use FF instead 09 ?
Or change function "accents, _, tags = item.partition(b'\t')" to searching x09 from end of string.

split_index = item.rfind(b'\t') # Reverse find the last `\t`
accents_part =  item[:split_index]
tag_part =  item[split_index + 1:]

accents = [int(b) for b in accents_part if b]

**Comment by magicse** [comment]
After changes in stressify_.py  for correct process when  Tag separator \t =09 and pos = 09
```
def _parse_dictionary_value(value):
    accents_by_tags = []
    
    if b'\n' not in value:
        # single item, all record is accent positions
        accents = [int(b) for b in value]
        tags = []
        accents_by_tags.append((tags, accents))

    else:
        # words whose accent position depends on POS and other tags
        items = value.split(b'\n')
        for item in items:
            if item:
                #accents, _, tags = item.partition(b'\t')
                split_index = item.rfind(b'\t') # Reverse find the last \t
                accents = item[:split_index]
                tags = item[split_index + 1:]
                
                accents = [int(b) for b in accents]
                tags = decompress_tags(tags)
                accents_by_tags.append((tags, accents))

    return accents_by_tags
```

i get correct first record result
```
Z:\1>test.py
викладачу´-предме´тнику
Z:\1>
```

**Comment by magicse** [comment]
Same problem could be for example for word пополасувала
Where пополасувала has two stress in position x06 and x0A  where x0A is \n

Compiled string from dictionary - пополасувала: b'\x06\n'
May be need change separators for \n and \t to for example FF and 7F to avoid crossing with position numbers x09 and x0A?

**Comment by magicse** [comment]
I select all words from stress.txt file with Accent Position 10 - x0A aka same as record separator \n and there are about 115000 words in the list.
I couldn't get Accent for any of this words from list. And all this due mismatch pos 10 and same code of record  divider \n
I think that  we get same problem with another words where positions will be  10 and 09 aka \n \t.
Please could you change \t with xFE and \n with xFF to avoide this problems.

I could make changes by myself but i dont have original dictionary with tags like ulif_accents.csv.
```
form,tag,type
поперева́люваного,множина,іменник
їді́,однина давальний,іменник жіночого
ї́ді,однина місцевий,іменник жіночого
```
Of  course I could recompile stress.txt  without  tags but the meaning of stanza module will be  lost. 
And then i need  to remove this module from the code so that it does not waste time.
I dont know what to do... but 115000 words is so mutch.
[FilteredWords.txt](https://github.com/user-attachments/files/17177354/FilteredWords.txt)

**Comment by osyvokon** [comment]
@magicse, thanks for the detailed report! I'll update the separator symbol and the splitting logic.

**Comment by osyvokon** [comment]
@magicse, this should be fixed in `ukrainian_word_stress==1.1.1`. Please check if it helps.

**Comment by magicse** [comment]
Hi @osyvokon 
Thank you very much, now it works as it should and without errors. 
Thanks again for your work.

**Comment by magicse** [comment]
close
